jobs:
  test:
    steps:
      - checkout
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
      - run:
          command: yarn test:all
orbs:
  node: circleci/node@2.0.3
version: 2.1
workflows:
  test:
    jobs:
      - test
