jobs:
  install-packages:
    steps:
      - checkout
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
      - run:
          command: npm run test
orbs:
  node: circleci/node@2.0.3
version: 2.1
workflows:
  test:
    jobs:
      - install-packages
      - node/test:
          run-command: test:all
          pkg-manager: yarn
