jobs:
  install-packages:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
orbs:
  node: circleci/node@2.0.3
version: 2.1
workflows:
  test:
    jobs:
      - install-packages
      - node/test:
          run-command: test:all
          pkg-manager: yarn
